# Generated by Django 5.2.14 on 2026-05-22 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '__first__'),
        ('coaches', '__first__'),
        ('training', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('group_voting', 'Group Voting'), ('group_approved', 'Group Approved'), ('coach_review', 'Coach Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='training.sessionoccurrence')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_reviews', to='coaches.coach')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('guardian_name', models.CharField(blank=True, max_length=160)),
                ('guardian_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('preference_type', models.CharField(choices=[('alone', 'Alone'), ('partner', 'With Partner'), ('group', 'In a Group')], default='alone', max_length=10)),
                ('preferred_days', models.JSONField(blank=True, default=list, help_text="e.g. ['sunday','wednesday']")),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred session time', null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('linked_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_of', to='players.player')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to='players.player')),
            ],
            options={
                'verbose_name_plural': 'Loyalty points',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancellationVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved', models.BooleanField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='players.cancellationrequest')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_votes', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='players.player'),
        ),
        migrations.CreateModel(
            name='AttendanceStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_attended_at', models.DateTimeField(blank=True, null=True)),
                ('streak_started_at', models.DateTimeField(blank=True, null=True)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='players.player')),
            ],
            options={
                'verbose_name_plural': 'Attendance streaks',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerCoach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_links', to='coaches.coach')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_links', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='players.referralcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['academy', 'created_at'], name='players_pla_academy_b76dff_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['academy', 'status'], name='players_pla_academy_9aeab4_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['academy', 'last_name'], name='players_pla_academy_e81823_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypoints',
            index=models.Index(fields=['academy', 'created_at'], name='players_loy_academy_171ead_idx'),
        ),
        migrations.AddIndex(
            model_name='cancellationvote',
            index=models.Index(fields=['academy', 'created_at'], name='players_can_academy_8729f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='cancellationvote',
            constraint=models.UniqueConstraint(fields=('request', 'voter'), name='uniq_vote_per_player'),
        ),
        migrations.AddIndex(
            model_name='cancellationrequest',
            index=models.Index(fields=['academy', 'created_at'], name='players_can_academy_ad1807_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancestreak',
            index=models.Index(fields=['academy', 'created_at'], name='players_att_academy_869ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='playercoach',
            index=models.Index(fields=['academy', 'created_at'], name='players_pla_academy_080003_idx'),
        ),
        migrations.AddConstraint(
            model_name='playercoach',
            constraint=models.UniqueConstraint(fields=('player', 'coach'), name='uniq_player_coach'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['academy', 'created_at'], name='players_ref_academy_f66f42_idx'),
        ),
    ]
