# Generated by Django 5.2.14 on 2026-05-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_real_changes'),
    ]

    operations = [
    ]
