# Generated by Django 5.2.14 on 2026-05-22 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0001_initial'),
        ('coaches', '0001_initial'),
        ('groups', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('recurrence', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=10)),
                ('weekly_mask', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('notes', models.TextField(blank=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('coaches', models.ManyToManyField(blank=True, related_name='series', to='coaches.coach')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='groups.group')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='training.venue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('coaches', models.ManyToManyField(blank=True, related_name='occurrences', to='coaches.coach')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='groups.group')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='training.sessionseries')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='training.venue')),
            ],
            options={
                'ordering': ['starts_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='players.player')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.sessionoccurrence')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['academy', 'created_at'], name='training_se_academy_9e69bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('occurrence', 'player'), name='uniq_occurrence_player')],
            },
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['academy', 'created_at'], name='training_ve_academy_6d6457_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionseries',
            index=models.Index(fields=['academy', 'created_at'], name='training_se_academy_ea4a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['academy', 'created_at'], name='training_se_academy_c7af0a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['academy', 'starts_at'], name='training_se_academy_7fa9ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['academy', 'status'], name='training_se_academy_ecc83e_idx'),
        ),
    ]
