# Generated by Django 5.2.14 on 2026-05-22 14:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0001_initial'),
        ('coaches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('age_min', models.PositiveSmallIntegerField(default=0)),
                ('age_max', models.PositiveSmallIntegerField(default=99)),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('primary_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_groups', to='coaches.coach')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='groups.GroupMembership', to='players.player'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='academies.academy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['academy', 'created_at'], name='groups_grou_academy_3ecfb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'player'), name='uniq_group_player'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['academy', 'created_at'], name='groups_grou_academy_deedfb_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['academy', 'created_at'], name='groups_venu_academy_bb5154_idx'),
        ),
    ]
